apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sainandan-mn/cloud-native-ecommerce-devops.git
    targetRevision: main
    path: kubernetes/product-catalog

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

